version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - ../../:/repo
      - .:/site
      - jekyll-bundle:/usr/local/bundle
    working_dir: /site
    environment:
      - JEKYLL_ENV=development
    command: bash -c "cp /repo/README.md /site/index.md && mkdir -p /site/assets && cp -r /repo/assets/images /site/assets/ && bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling"

volumes:
  jekyll-bundle:
